let listNotifi = [
    {
        avatar: 'https://yt3.ggpht.com/524B3R1SLC5PWDi5GmEa6BdyF1kYEdHlc8wVVTMZ3OeUNtfh0AaFYnGF7vIb5mKeGYJKIn02GBo=s88-c-k-c0x00ffffff-no-rj',
        title: 'Bỏ ra 60 triệu mua iPhone 14 Pro Max sớm nhất Việt Nam: Đầy rủi ro! | Vật Vờ Studio',
        thumbnail: 'https://i.ytimg.com/vi/nZlJMVLOusQ/hqdefault.jpg',
        time: '21 phút trước',
        chanel: 'VTV 24h',
        isSeen: false,
    },
    {
        avatar: 'https://yt3.ggpht.com/524B3R1SLC5PWDi5GmEa6BdyF1kYEdHlc8wVVTMZ3OeUNtfh0AaFYnGF7vIb5mKeGYJKIn02GBo=s88-c-k-c0x00ffffff-no-rj',
        title: 'Bỏ ra 60 triệu mua iPhone 14 Pro Max sớm nhất Việt Nam: Đầy rủi ro! | Vật Vờ Studio',
        thumbnail: 'https://i.ytimg.com/vi/nZlJMVLOusQ/hqdefault.jpg',
        time: '21 phút trước',
        chanel: 'VTV 24h',
        isSeen: true,
    },
    {
        avatar: 'https://yt3.ggpht.com/524B3R1SLC5PWDi5GmEa6BdyF1kYEdHlc8wVVTMZ3OeUNtfh0AaFYnGF7vIb5mKeGYJKIn02GBo=s88-c-k-c0x00ffffff-no-rj',
        title: 'Bỏ ra 60 triệu mua iPhone 14 Pro Max sớm nhất Việt Nam: Đầy rủi ro! | Vật Vờ Studio',
        thumbnail: 'https://i.ytimg.com/vi/nZlJMVLOusQ/hqdefault.jpg',
        time: '21 phút trước',
        chanel: 'VTV 24h',
        isSeen: false,
    },
    {
        avatar: 'https://yt3.ggpht.com/524B3R1SLC5PWDi5GmEa6BdyF1kYEdHlc8wVVTMZ3OeUNtfh0AaFYnGF7vIb5mKeGYJKIn02GBo=s88-c-k-c0x00ffffff-no-rj',
        title: 'Bỏ ra 60 triệu mua iPhone 14 Pro Max sớm nhất Việt Nam: Đầy rủi ro! | Vật Vờ Studio',
        thumbnail: 'https://i.ytimg.com/vi/nZlJMVLOusQ/hqdefault.jpg',
        time: '21 phút trước',
        chanel: 'VTV 24h',
        isSeen: false,
    },
    {
        avatar: 'https://yt3.ggpht.com/524B3R1SLC5PWDi5GmEa6BdyF1kYEdHlc8wVVTMZ3OeUNtfh0AaFYnGF7vIb5mKeGYJKIn02GBo=s88-c-k-c0x00ffffff-no-rj',
        title: 'Bỏ ra 60 triệu mua iPhone 14 Pro Max sớm nhất Việt Nam: Đầy rủi ro! | Vật Vờ Studio',
        thumbnail: 'https://i.ytimg.com/vi/nZlJMVLOusQ/hqdefault.jpg',
        time: '21 phút trước',
        chanel: 'VTV 24h',
        isSeen: true,
    },
    {
        avatar: 'https://yt3.ggpht.com/524B3R1SLC5PWDi5GmEa6BdyF1kYEdHlc8wVVTMZ3OeUNtfh0AaFYnGF7vIb5mKeGYJKIn02GBo=s88-c-k-c0x00ffffff-no-rj',
        title: 'Bỏ ra 60 triệu mua iPhone 14 Pro Max sớm nhất Việt Nam: Đầy rủi ro! | Vật Vờ Studio',
        thumbnail: 'https://i.ytimg.com/vi/nZlJMVLOusQ/hqdefault.jpg',
        time: '21 phút trước',
        chanel: 'VTV 24h',
        isSeen: false,
    },
    {
        avatar: 'https://yt3.ggpht.com/524B3R1SLC5PWDi5GmEa6BdyF1kYEdHlc8wVVTMZ3OeUNtfh0AaFYnGF7vIb5mKeGYJKIn02GBo=s88-c-k-c0x00ffffff-no-rj',
        title: 'Bỏ ra 60 triệu mua iPhone 14 Pro Max sớm nhất Việt Nam: Đầy rủi ro! | Vật Vờ Studio',
        thumbnail: 'https://i.ytimg.com/vi/nZlJMVLOusQ/hqdefault.jpg',
        time: '21 phút trước',
        chanel: 'VTV 24h',
        isSeen: false,
    },
    {
        avatar: 'https://yt3.ggpht.com/524B3R1SLC5PWDi5GmEa6BdyF1kYEdHlc8wVVTMZ3OeUNtfh0AaFYnGF7vIb5mKeGYJKIn02GBo=s88-c-k-c0x00ffffff-no-rj',
        title: 'Bỏ ra 60 triệu mua iPhone 14 Pro Max sớm nhất Việt Nam: Đầy rủi ro! | Vật Vờ Studio',
        thumbnail: 'https://i.ytimg.com/vi/nZlJMVLOusQ/hqdefault.jpg',
        time: '21 phút trước',
        chanel: 'VTV 24h',
        isSeen: true,
    },
    {
        avatar: 'https://yt3.ggpht.com/524B3R1SLC5PWDi5GmEa6BdyF1kYEdHlc8wVVTMZ3OeUNtfh0AaFYnGF7vIb5mKeGYJKIn02GBo=s88-c-k-c0x00ffffff-no-rj',
        title: 'Bỏ ra 60 triệu mua iPhone 14 Pro Max sớm nhất Việt Nam: Đầy rủi ro! | Vật Vờ Studio',
        thumbnail: 'https://i.ytimg.com/vi/nZlJMVLOusQ/hqdefault.jpg',
        time: '21 phút trước',
        chanel: 'VTV 24h',
        isSeen: false,
    },
    {
        avatar: 'https://yt3.ggpht.com/524B3R1SLC5PWDi5GmEa6BdyF1kYEdHlc8wVVTMZ3OeUNtfh0AaFYnGF7vIb5mKeGYJKIn02GBo=s88-c-k-c0x00ffffff-no-rj',
        title: 'Bỏ ra 60 triệu mua iPhone 14 Pro Max sớm nhất Việt Nam: Đầy rủi ro! | Vật Vờ Studio',
        thumbnail: 'https://i.ytimg.com/vi/nZlJMVLOusQ/hqdefault.jpg',
        time: '21 phút trước',
        chanel: 'VTV 24h',
        isSeen: false,
    },
    {
        avatar: 'https://yt3.ggpht.com/524B3R1SLC5PWDi5GmEa6BdyF1kYEdHlc8wVVTMZ3OeUNtfh0AaFYnGF7vIb5mKeGYJKIn02GBo=s88-c-k-c0x00ffffff-no-rj',
        title: 'Bỏ ra 60 triệu mua iPhone 14 Pro Max sớm nhất Việt Nam: Đầy rủi ro! | Vật Vờ Studio',
        thumbnail: 'https://i.ytimg.com/vi/nZlJMVLOusQ/hqdefault.jpg',
        time: '21 phút trước',
        chanel: 'VTV 24h',
        isSeen: true,
    },
    {
        avatar: 'https://yt3.ggpht.com/524B3R1SLC5PWDi5GmEa6BdyF1kYEdHlc8wVVTMZ3OeUNtfh0AaFYnGF7vIb5mKeGYJKIn02GBo=s88-c-k-c0x00ffffff-no-rj',
        title: 'Bỏ ra 60 triệu mua iPhone 14 Pro Max sớm nhất Việt Nam: Đầy rủi ro! | Vật Vờ Studio',
        thumbnail: 'https://i.ytimg.com/vi/nZlJMVLOusQ/hqdefault.jpg',
        time: '21 phút trước',
        chanel: 'VTV 24h',
        isSeen: false,
    },
];
export default listNotifi;
